pipeline {
    agent {
        docker {
            image 'my-cicd-agent'
            // We need to keep this args for the agent to use Docker
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t cicd-demo:v2 .'
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Running container test...'
                sh 'docker run --rm cicd-demo:v2 echo "Container is working fine"'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying to Kubernetes...'
                writeFile file: 'deployment.yaml', text: '''apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: cicd-demo
          image: cicd-demo:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
'''
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}